### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by annabelleee** [archesproject/v5_demo#3]
Icon missing:

![image](https://user-images.githubusercontent.com/16655095/77213363-cf77ea00-6ac7-11ea-8b31-a9b379b0aa05.png)

**Comment by ryan86** [comment]
Completed 3/21, assigned to Annabel to QA.

Added `Alias /media/ /home/ubuntu/static/` to apache config so /media/img/inspection.png would point to the correct location.

**Comment by annabelleee** [comment]
![image](https://user-images.githubusercontent.com/16655095/77361794-2cb0ad00-6d0d-11ea-91ab-841da5334958.png)
