### ISSUE TITLE
Saved search background images won't load

### ISSUE THREAD

**Issue by annabelleee** [archesproject/v5_demo#4]
Can't add a background image for saved search:

![image](https://user-images.githubusercontent.com/16655095/77213708-08fd2500-6ac9-11ea-8d5b-3c5a9e937c6d.png)

After this screen, this is what loaded in the saved search panel (no image):
![image](https://user-images.githubusercontent.com/16655095/77213892-bc661980-6ac9-11ea-871b-2ce8b8c90cc9.png)

**Comment by ryan86** [comment]
Completed 3/21, assigned to Annabel to QA.

Apache needed permissions on uploaded files directory. 

`sudo chgrp www-data uploadedfiles`

**Comment by annabelleee** [comment]
Works!
![Uploading image.png…]()
