### ISSUE TITLE
v5 demo instance: Connect to Arches Collector

### ISSUE THREAD

**Issue by annabelleee** [archesproject/v5_demo#5]
Currently can't connect v5 demo instance to Arches Collector. Please check settings for connecting to Arches Collector.

**Comment by ryan86** [comment]
Completed 3/21, assigned to Annabel to QA.

Followed instructions here: https://arches.readthedocs.io/en/stable/api/#registering-an-application-with-arches

Added `WSGIPassAuthorization on` to apache config file.

**Comment by annabelleee** [comment]
Both Lindsey and I were able to pull the sample project from the instance.
