### ISSUE TITLE
v5 demo instance: sign-up error/process

### ISSUE THREAD

**Issue by annabelleee** [archesproject/v5_demo#6]
While trying to sign-up, the following error appears:
![image](https://user-images.githubusercontent.com/16655095/77361121-ec046400-6d0b-11ea-91ac-29b097c0af24.png)

Also, signing up should automatically add the user to the Resource Editor group. 

Let me know where I can edit the email message that initially gets sent out after signing in.

**Comment by ryan86** [comment]
Completed 3/25, assigned to Annabel for QA.

Added the following settings to settings_local.py:
```
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = ***email address***
EMAIL_HOST_PASSWORD = ***password***
EMAIL_PORT = 587

RECAPTCHA_PUBLIC_KEY = ***public key***
RECAPTCHA_PRIVATE_KEY = ***private key***

USER_SIGNUP_GROUP = 'Resource Editor'
```
Note: We'll have to add the final domain to the captcha dashboard when we have one.

Email verbage located at: https://github.com/archesproject/arches/blob/master/arches/app/views/auth.py#L115

**Comment by annabelleee** [comment]
Notes on signup process: 

- updated email text in auth.py and added to v5_demo repo:
https://github.com/archesproject/v5_demo/blob/master/v5_demo/views/auth.py

- updated text on signup and login pages and added files to v5_demo repo:
https://github.com/archesproject/v5_demo/blob/master/v5_demo/templates/login.htm
https://github.com/archesproject/v5_demo/blob/master/v5_demo/templates/signup.htm

- updated text on password recovery pages (see #8 for additional work on password recovery page)
https://github.com/archesproject/v5_demo/blob/master/v5_demo/templates/registration/password_reset_form.html
https://github.com/archesproject/v5_demo/blob/master/v5_demo/templates/registration/password_reset_confirm.html
