### ISSUE TITLE
Saved Searches overlapping

### ISSUE THREAD

**Issue by annabelleee** [archesproject/v5_demo#7]
Saved Searches are overlapping in the display panel:

![image](https://user-images.githubusercontent.com/16655095/78610513-d584ff00-7819-11ea-96a1-af28bc5c1f20.png)

This has happened on the initial load of the page, and only clears after restoring down/resizing the tab/window.

**Comment by annabelleee** [comment]
When scrolling the saved searches at the end are overlapping, especially when adding more saved searches.

**Comment by ryan86** [comment]
Fixed 5/19. Waiting for Annabel sign off before committing to core repo.
